# 站点信息配置
site_name: 知识与技能图景
# site_description:
# site_url: 'http://jokerleu.github.io'
site_author: jokerleu


# git相关配置-右上角
repo_name: 'jokerleu'
repo_url: 'https://github.com/jokerleu'


# 主题配置
theme:
  name: material
  highlightjs: true
  hljs_style: 'Xt 256'
  hljs_languages:
    - yaml
    - rust
  palette:
    # primary: 'Blue Grey'
    primary: 'White'
    accent: 'Blue'
  feature:
    tabs: false
  # 语言设为中文
  language: 'zh'
  shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s


# 额外配置
extra:
  # 右下角
  social:
    - type: github
      link: https://github.com/jokerleu
  # 搜索设为日本即可中文搜索
  search:
    language: 'jp'


# 额外脚本配置
extra_javascript:
  - 'js/extra.js'
#  - 'js/baidu-tongji.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'


# markdown扩展配置,一般不需要修改
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde


# 导航菜单配置
nav:
  - 容器云技术:
    - Docker:
      - Docker基础: 
        - '01-Docker介绍': 'docker/01-Docker基础使用/01-Docker介绍.md'
        - '02-Docker网络和存储': 'docker/01-Docker基础使用/02-Docker数据存储和网络访问.md'
        - '03-镜像的构建': 'docker/01-Docker基础使用/03-手动构建镜像.md'
        - '04-Dockerfle': 'docker/01-Docker基础使用/04-DockerFile.md'
    - Kubernetes编排:
      - '01-k8s纯手工部署': 'kubernetes/01-k8s纯手工部署.md'
  - Django学习笔记:
    - 'Django DRF':
      - '01-Restful介绍': django/DRF/01-Restful.md
      - '02-Request封装': django/DRF/02-Request的封装.md
      - '03-DRF的认证': django/DRF/03-DRF的认证.md
      - '04-DRF的权限': django/DRF/04-DRF权限.md 
      - '05-DRF访问限制': django/DRF/05-DRF访问限制.md
      - '06-DRF版本&解析器': django/DRF/06-DRF版本&解析器.md
      - '07-DRF序列化': django/DRF/07-DRF序列化.md
  - 未分类页面:
    - Linux内核: linux内核.md
  - 计算机:
    - '操作系统':
      - '01-Docker介绍': 'docker/01-Docker基础使用/01-Docker介绍.md'
    - '编程语言':
      - '01-Docker介绍': 'docker/01-Docker基础使用/01-Docker介绍.md'
    - '网络':
      - '01-Docker介绍': 'docker/01-Docker基础使用/01-Docker介绍.md'
    - '安全':
      - '01-Docker介绍': 'docker/01-Docker基础使用/01-Docker介绍.md'
    - '弱电':
      - '01-Docker介绍': 'docker/01-Docker基础使用/01-Docker介绍.md'
    - '运维':
      - '01-Docker介绍': 'docker/01-Docker基础使用/01-Docker介绍.md'
    - 'IoT物联网':
      - '01-Docker介绍': 'docker/01-Docker基础使用/01-Docker介绍.md'
    - '工作未分类':
      - '01-Docker介绍': 'docker/01-Docker基础使用/01-Docker介绍.md'
    - '网站收藏':
      - '测试页面': '计算机/测试用.md'
